name: Install Dependencies

runs:
  using: composite
  steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "Install Linux dependencies"
        sudo apt-get update
        sudo apt-get install -y libgmp-dev gperf
        sudo apt-get install -y python3-pip
        sudo apt-get install -y lcov
        sudo gem install coveralls-lcov
        echo "Install Linux dependencies [DONE]"
    - name: Install macOS Dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        echo "Install macOS dependencies"
        brew update
        brew install gmp gperf python3 lcov
        sudo gem install coveralls-lcov
        echo "Install macOS dependencies [DONE]"
