.TH YICES-SAT 1 "June 2024" "Yices 2.6.5" "User Commands"
.SH NAME
yices-sat \- the Yices Sat solver
.SH SYNOPSIS
.B yices-sat
[
.I options
]
.I file
.SH DESCRIPTION
Runs the Yices SAT solver on an input file in the DIMACS format.
.
.SH OPTIONS
.TP
.B \-\-version,  \-V
Display version and exit.
.TP
.B \-\-help,  \-h
Display a short help summary.
.TP
.TP
.B \-\-model,  \-m
Print a model on stdout if the problem is satisfiable.
.TP
.B \-\-verbose,  \-v
Print statistics and other data during the search.
.TP
.B \-\-stats
Print a statistics summary at the end of the search.
.
.SH SEE ALSO
.BR yices (1),
.BR yices-smt (1),
.BR yices-smt2 (1)
.PP
For bug reporting and other information, please visit http://yices.csl.sri.com.
.
.SH AUTHORS
.PP
Copyright (C) SRI International.
.PP
Yices is developed at SRI's Computer Science Laboratory. The main developers
are Bruno Dutertre <bruno@csl.sri.com>, Dejan Jovanovic <dejan@csl.sri.com>, Ian A. Mason <iam@csl.sri.com>,
and Stephane Graham-Lengrand <stephane.graham-lengrand@sri.com>.
