.TH YICES "1" "June 2017" "Yices 2.6.0. Copyright SRI International." "User Commands"
.SH NAME
yices-sat \- the Yices sat solver
.SH SYNOPSIS
.B yices-sat
[\fIoptions\fR] \fIfilename\fR
.SH DESCRIPTION
.SS "Option summary:"
.TP
\fB\-\-version\fR, \fB\-V\fR
Show version and exit
.TP
\fB\-\-help\fR, \fB\-h\fR
Print this message and exit
.TP
\fB\-\-model\fR, \fB\-m\fR
Show a model if the problem is satisfiable
.TP
\fB\-\-verbose\fR, \fB\-v\fR
Print statistics during the search
.TP
\fB\-\-stats\fR
Print statistics at the end of the search
.PP
For bug reporting and other information, please see http://yices.csl.sri.com/
.PP
Build date: 2017\-06\-08
Platform: x86_64\-unknown\-linux\-gnu (release)
.SH SEE ALSO
.XR yices 1 ,
.XR yices-sat 1 ,
.XR yices-smt 1 ,
.XR yices-smt2 1 ,
.SH AUTHORS
.AN Bruno Dutertre Aq Mt bruno@csl.sri.com
.AN Dejan Jovanovic Aq Mt dejan@csl.sri.com
