#!/bin/sh
#
# Copyright (c) 2026, SRI International
# SPDX-License-Identifier: BSD-3-Clause
#

if [ "$USER " = " " ]; then
  user=`sh -c whoami 2>/dev/null`

  if [ "$user " = " " ]; then
     user=`sh -c /usr/ucb/whoami 2>/dev/null`;
     if [ "$user " = " " ]; then
        user=$LOGNAME;
        if [ "$user " = " " ]; then
           user=bigloo
        fi
     fi
  fi
else
  user=$USER
fi

echo $user
