#!/bin/bash
#
# Copyright (c) 2026, SRI International
# SPDX-License-Identifier: BSD-3-Clause
#


#
# Setup environment variables to run the Visual
# Studio 2013 command-line tools from Cygwin
#
vsbase="/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 12.0"
export PATH=${vsbase}/VC/bin:${vsbase}/Common7/IDE:${PATH}
